name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Extract version from package.json
        id: extract_version
        run: echo ::set-output name=version::$(node -pe "require('./package.json').version")

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "simple-node-serv"
          heroku_email: "igor.karpyuk00@gmail.com"

      - name: Update Heroku Config Vars
        run: |
          heroku config:set GITHUB_RELEASE_VERSION=${{ steps.extract_version.outputs.version }} --app simple-node-serv
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
